[package]
name = "apps"
version = "0.5.0"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "radar"
path = "src/radar.rs"

[[bin]]
name = "1090"
path = "src/1090.rs"

[dependencies]
adsb_deku = { path = "../", version = "0.5" }
hex = "0.4"
crossterm = "0.21"
clap = {version = "3.0.0-rc.0", features = ["color", "derive"]}
# CHANGE WHEN https://github.com/fdehau/tui-rs/issues/529 is released
#tui = {version = "0.16", default-features = false, features = ["crossterm"]}
tui = { git = "https://github.com/fdehau/tui-rs.git", branch = "master", features = ["crossterm"] }
gpsd_proto = "0.7.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
anyhow = { version = "1.0", features = ["backtrace"] }
