[package]
name = "rsadsb_apps"
version = "0.5.1"
license = "MIT"
edition = "2021"
rust-version = "1.59.0"

[[bin]]
name = "radar"
path = "src/radar.rs"

[[bin]]
name = "1090"
path = "src/1090.rs"

[dependencies]
adsb_deku = { path = "../libadsb_deku", version = "0.5" }
hex = "0.4"
crossterm = "0.22"
clap = {version = "3.1.0", features = ["color", "derive", "wrap_help"]}
tui = "0.17"
gpsd_proto = "0.7.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
anyhow = { version = "1.0", features = ["backtrace"] }
csv = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.19"
